// Generated by LiveScript 1.6.0
(function(){
  module.exports = function(){
    var s4;
    s4 = function(){
      return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
    };
    return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
  };
}).call(this);
