// Generated by LiveScript 1.6.0
(function(){
  var toString$ = {}.toString;
  module.exports = function(str, cb){
    var err;
    if (toString$.call(str).slice(8, -1) !== 'String') {
      return cb("FATAL. Expected string");
    }
    try {
      return cb(null, JSON.parse(str));
    } catch (e$) {
      err = e$;
      return cb(err);
    }
  };
}).call(this);
